# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampost',
            options={'ordering': ['-post_date', '-last_updated_at']},
        ),
    ]
