# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_runpost_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
